### ISSUE TITLE
UsersIdentityResponse missing possible data

### ISSUE THREAD

**Issue by jasonmullins** [seratch/jslack#1]
Hi, thanks for creating an awesome library.  I have a question.  I noticed there is more data that could be available on this method:  https://api.slack.com/methods/users.identity... like avatars, team name, etc.

I was going to clone the repo and add it but I can't really get it to build.  Is there something I need to do to get it to build successfully?

**Comment by seratch** [comment]
>I can't really get it to build. Is there something I need to do to get it to build successfully?

You must be able to build this project with Maven 3. One thing, this project uses Lombok to reduce boilerplate code. If you're trying to build on your IDE, ensure the annotation processing tool settings.

I'm looking forward to merging your pull request!
