### ISSUE TITLE
chatUpdate does not support Blocks

### ISSUE THREAD

**Issue by meledin** [seratch/jslack#104]
`chatPostMessage` is able to submit a block due to the following code.

```
        if (req.getBlocks() != null) {
            String json = GsonFactory.createSnakeCase().toJson(req.getBlocks());
            form.add("blocks", json);
        }
```

While the `chat.update` method in the Slack API [supports](https://api.slack.com/methods/chat.update) processing blocks, the same method is not available in the jslack API, I assume due to an omission.

**Comment by seratch** [comment]
@meledin Thanks. You're right. We need to support `chat.postEphemeral` and `chat.update` as well. I just pushed a change to fix this at https://github.com/seratch/jslack/commit/9132336608e29acea7f19647fa7ace97f3f5ded7 I will make sure if it surely works later.
