### ISSUE TITLE
RTMClient may stop receiving events from Slack Platform

### ISSUE THREAD

**Issue by stefan-reich** [seratch/jslack#109]
Hi, is this a known issue?

When the bot runs for a longer time, sometimes it stops receiving messages from Slack. :/

Restarting the library is probably easy... but the major question here is how I would even detect the problem from within the bot. The bot just thinks there are no new events.

Edit 1: I investigated a bit and RTMClient.currentSession is null.

Edit 2: Ah, I should add an error handler. I was not receiving log messages from jSlack. How would I reconnect to Slack on error? Call disconnect() and then connect()?

**Comment by seratch** [comment]
As long as the underlying wss uri is vaild, calling `rtm.disconnect()` and `rtm.connect()` then should work for you.

**Comment by seratch** [comment]
I realized that disconnect and connect doesn’t work. I started working on improvements of RTMClient. Will make a PR and ship a new version including those soon.

**Comment by seratch** [comment]
@stefan-reich I've implemented `reconnect()` method in `RTMClient`. This one does a complete refresh of the client state. Calling `disconnect()` then `reconnect()` should be effective for the case. If you try the method out and find it seems to be working well, I would like you to close this issue then.

**Comment by seratch** [comment]
The source code: https://github.com/seratch/jslack/blob/1.3.0/src/main/java/com/github/seratch/jslack/api/rtm/RTMClient.java#L101-L117

**Comment by stefan-reich** [comment]
Thanks. I don't think I am seeing any errors though, apparently the connection dies silently...

**Comment by seratch** [comment]
If you’re using an old version, the situation might happen because old implementation terminates the connection once it receives an error in a session. Could you try the latest version?

**Comment by stefan-reich** [comment]
OK, I upgraded to 1.4.2

**Comment by seratch** [comment]
I believe this issue is no longer happening. Please allow me to close this in a few days.

**Comment by seratch** [comment]
Allow me to close this issue. Please feel free to reopen this when you have any further topics to discuss here.
