### ISSUE TITLE
Question: Cannot compile the code without annotation processor settings

### ISSUE THREAD

**Issue by duchino** [seratch/jslack#113]
I cannot build the lib.
for example Slack.jave this builder() method is not in WebhookResponse
```
        return WebhookResponse.builder()
                .code(httpResponse.code())
                .message(httpResponse.message())
                .body(body)
                .build();
    }
```

**Comment by seratch** [comment]
@duchino This library depends on [Lombok](https://projectlombok.org/). Enable annotation processors on your IDE.

**Comment by seratch** [comment]
@duchino Can I close this issue if you don't have updates?

**Comment by seratch** [comment]
Please allow me to close this issue. If you have something to add or discuss further, please feel free to reopen it.
