### ISSUE TITLE
Events API | incoming json is not deserialized to the respective payload completely

### ISSUE THREAD

**Issue by shubhvashisht** [seratch/jslack#121]
I am using jslack's event dispatcher feature to handle the incoming events from the event APIs and get the payload generated from SDK itself. 

It appears that the SDK is not generating the complete payload successfully and is dropping some attributes form the incoming JSON. 

As per my analysis the attributes where there is "camelCasing" are getting dropped from the converted object. Further, it appears that the custom GsonFactory() is using the field naming policy which might me the root cause of this issue.

This SDK is really powerful and if we could get this fixed sooner then it will really help us in expediting our integration with Slack.

Incoming JSON:

{
  "token": "ABC",
  "teamId": "TBC",
  "apiAppId": "ASDA",
  "event": {
    "type": "message",
    "channel": "ASDA",
    "user": "TEST",
    "text": "hi",
    "ts": "1554965364.000400",
    "eventTs": "1554965364.000400",
    "channelType": "im",
    "hidden": false,
    "is_starred": false
  },
  "type": "event_callback",
  "authedUsers": [
    "SDFGSG"
  ],
  "eventId": "SDFSF",
  "eventTime": 1554965364
}

converted object :

{
  "token": "ABC",
  "event": {
    "type": "message",
    "channel": "ASDA",
    "user": "TEST",
    "text": "hi",
    "ts": "1554965364.000400",
    "hidden": false,
    "is_starred": false
  },
  "type": "event_callback"
}

**Comment by shubhvashisht** [comment]
sorry, this is not an issue. I somehow had the incorrect input JSON.

**Comment by seratch** [comment]
You're an early adopter! Thank you for using the event dispatcher.
