### ISSUE TITLE
InputStream from response

### ISSUE THREAD

**Issue by namedgraph** [seratch/jslack#126]
Hi, how can I get an `InputStream` from `ConversationsHistoryResponse` (or any `Response` really)? I want to read raw JSON data.

**Comment by namedgraph** [comment]
Example from Google's api-client-library:
https://developers.google.com/api-client-library/java/google-api-java-client/reference/1.20.0/com/google/api/client/googleapis/services/AbstractGoogleClientRequest#executeAsInputStream()

**Comment by seratch** [comment]
You can access raw okhttp responses if you write some similar code to this internal method. https://github.com/seratch/jslack/blob/1.4.3/src/main/java/com/github/seratch/jslack/api/methods/impl/MethodsClientImpl.java#L1437

**Comment by seratch** [comment]
okhttp’s Response class offers a method to extract request body data as input stream.

**Comment by namedgraph** [comment]
I'm looking into it. Some remarks:

I think if `ChannelsHistoryRequest` and similar would be based on a map and extend `FormBody.Builder`, there would be no need to do the mappings between the two in `MethodsClientImpl` and the code would be much more generic.

I think Google client's approach

    Request req = service.method();
    Response resp = req.execute();

is more flexible than

    Request req = Request.builder()...build();
    Response resp = service.method().execute(req);

because it allows the `Request` to provide different forms of results without affecting the service interface.

**Comment by namedgraph** [comment]
I wrote such a method

    public static InputStream buildResponse(Response response) throws IOException, SlackApiException {
        if (response.code() == 200) {
            return response.body().byteStream();
        } else {
            String body = response.body().string();
            throw new SlackApiException(response, body);
        }
    }

but looks like it's too much work converting `ConversationsHistoryRequest` to `ConversationsHistoryResponse` so that I can feed it into the method above.

I think a more generic design would allow more flexibility here.

**Comment by seratch** [comment]
@namedgraph What do you think about #127 ? I'm going to merge the PR soon.

**Comment by seratch** [comment]
Please allow me to close this issue by #127.
