### ISSUE TITLE
Slash command response is only visible to the user instead of everyone in the channel. It appears that the "response_type" property is missing from the PayLoad builder class.

### ISSUE THREAD

**Issue by shubhvashisht** [seratch/jslack#140]
![image](https://user-images.githubusercontent.com/34352242/56929776-64788b80-6a8f-11e9-8cec-5d63acfa92f4.png)

**Comment by seratch** [comment]
`SlashCommandPayload` in this library means an incoming message from Slack Platform. 

To respond to the command execution, use `SlashCommandResponse` to build the response body.
* https://github.com/seratch/jslack/blob/1.5.2/src/main/java/com/github/seratch/jslack/app_backend/slash_commands/response/SlashCommandResponse.java#L14
* https://github.com/seratch/jslack/blob/1.5.2/src/main/java/com/github/seratch/jslack/app_backend/slash_commands/DelayedResponseSender.java#L23-L33

**Comment by seratch** [comment]
Could you close this issue if my answer is helpful?

**Comment by shubhvashisht** [comment]
thanks. I will review this.

**Comment by shubhvashisht** [comment]
Looks like 1.5.2 is a major change from 1.4.2.  Is there a documentation on
what changed?

**Comment by seratch** [comment]
The documents for new modules don’t exist yet. Will do later.

**Comment by seratch** [comment]
@shubhvashisht #142 should be helpful to know how to use them.
