### ISSUE TITLE
Chat fails when using a trustStore

### ISSUE THREAD

**Issue by maury33308** [seratch/jslack#143]
I need to make HTTPS calls to my server using a trustStore and when I add -Djava.net.ssl.trustStore=trustStore.jks to my application launch command, my calls to Slack fail with the error 'unable to find valid certification path to requested target'.

Is there a certificate I need to import into my trustStore so I can access both my application and Slack?

Thanks,

**Comment by seratch** [comment]
I'm not an expert on this matter yet but it seems that `okhttp` doesn't support the JVM option. Instead, we can call `OkHttpClient.Builder#sslSocketFactory(..)` in Java code to set up the configuration.

* https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#sslSocketFactory-javax.net.ssl.SSLSocketFactory-javax.net.ssl.X509TrustManager-
* https://stackoverflow.com/questions/23103174/does-okhttp-support-accepting-self-signed-ssl-certs
* https://gist.github.com/swankjesse/b8c289c8cf527d7e556b

**Comment by seratch** [comment]
@maury33308 Do you have any further comments? Otherwise, let me close this issue with a few days.

**Comment by seratch** [comment]
Allow me to close this issue. If you have more comments in the future, feel free to reopen.

**Comment by maury33308** [comment]
Yes thanks. We have resolved the problem.Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Kazuhiro Sera <notifications@github.com> Date : 01/07/2019  23:49  (GMT-05:00) À : seratch/jslack <jslack@noreply.github.com> Cc : maury33308 <mmills@polyres.com>, Mention <mention@noreply.github.com> Objet : Re: [seratch/jslack] Chat fails when using a trustStore (#143) Allow me to close this issue. If you have more comments in the future, feel free to reopen.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/seratch/jslack/issues/143?email_source=notifications\u0026email_token=AHLQ4NIPMDRY67MXAVESDJTP5LF27A5CNFSM4HJT55W2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY77DII#issuecomment-507507105",
"url": "https://github.com/seratch/jslack/issues/143?email_source=notifications\u0026email_token=AHLQ4NIPMDRY67MXAVESDJTP5LF27A5CNFSM4HJT55W2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODY77DII#issuecomment-507507105",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
