### ISSUE TITLE
state, notify_on_cancel are unsupported in dialogs.open API

### ISSUE THREAD

**Issue by shubhvashisht** [seratch/jslack#149]
The dialog class doesnt have the state and notify on cancel properties. These two properties are available as per Slack's documentation.

**Comment by seratch** [comment]
The documentation: https://api.slack.com/dialogs

**Comment by shubhvashisht** [comment]
by when this will be available to be downloaded from maven?

**Comment by seratch** [comment]
Just released 1.5.7. The version will be available on the Maven Central repositories within a few hours. https://github.com/seratch/jslack/compare/1.5.6...1.5.7
