### ISSUE TITLE
Library doesn't want to be compiled with 1.7 target

### ISSUE THREAD

**Issue by azakordonets** [seratch/jslack#15]
Hi, is it possible to use this library with java 1.6-1.7 in Android projects ? When i added it to our gradle build, i got this error : 

```
Error:Execution failed for task ':sdk:transformClassesWithDexForDebugAndroidTest'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/Users/andrewzakordonets/.m2/repository/com/github/seratch/jslack/1.0.8/jslack-1.0.8.jar' to '/Users/andrewzakordonets/Work/Vimpelcom/veon-sdk/sdk/build/intermediates/transforms/dex/androidTest/debug/folders/1000/10/jslack-1.0.8_6cfaf33714fc85887f68054544efa05c861e4aee'
```

**Comment by seratch** [comment]
Hmm, a shortcut class depends on java.util.Optional but others can be compatible with Java 7. If you'll seriously use this library, I'll consider supporting Java 7.

**Comment by azakordonets** [comment]
It's ok, i found https://github.com/pschroen/slack-api-android project , which i can use with Android apps. I like your api a bit more, but project does what i need as well. Thanks.
