### ISSUE TITLE
Add support of the BlockKit to attachments

### ISSUE THREAD

**Issue by efulmo** [seratch/jslack#157]
Ofgicial documentatiin claims to support `blocks` in attachment. Although there is a workaround for `chat.postMessage`, there is no such one for `chat.unfurl` that consumes only attachments. Please add it.

**Comment by seratch** [comment]
Thank you for this feature request. You're right. We should have `blocks` in an `Attachment`. https://api.slack.com/changelog/2018-12-a-bric-a-brac-of-broadcasts-built-with-blocks#how_do_i_prepare

I will work on it soon and the change will be included in a next release (possibly this weekend or early next week, JST)

**Comment by seratch** [comment]
Update: I'll work on this soon.

**Comment by seratch** [comment]
@efulmo I just started working on this. If I could know your needs correctly, it would be helpful.

>Although there is a workaround for chat.postMessage

Could you share your workaround with some code examples?

> there is no such one for chat.unfurl that consumes only attachments. Please add it

Could you share your ideal way to send blocks in the request?

**Comment by seratch** [comment]
Never mind regarding `chat.unfurl`. I still would like to know your workaround for `chat.postMessage`.

**Comment by efulmo** [comment]
Oh I just meant [ChatPostMessageRequest#blocks](https://github.com/seratch/jslack/blob/master/jslack-api-client/src/main/java/com/github/seratch/jslack/api/methods/request/chat/ChatPostMessageRequest.java#L55-L58) method. I see that you already implemented BlockKit in `chat.unfurl`.
