### ISSUE TITLE
iconEmoji is not displayed by Slack

### ISSUE THREAD

**Issue by anatolyw** [seratch/jslack#158]
In my Spring Component I have implemented PostConstruct to test that WebHook is configured properly as it is shown below. I see the message and attachment in Slack, but I don't see emoji.

```java
    @PostConstruct
    public void invokeSlackWebhook() {

        Attachment attachment = Attachment.builder()
                .text("Some attachment")
                .build();
        Payload payload = Payload.builder()
                .iconEmoji(":smiley_cat:") //TODO: doesn't work
                .text("Just to test Slack's incoming webhooks.")
                .attachments(List.of(attachment))
                .build();

        try {
            WebhookResponse response = slack.send(webhookUrl, payload);
            logger.info("Got response: {}", response);
        } catch (Exception e) {
            logger.error("Error posting to Slack Incoming Webhook: ", e);
        }
    }
```

**Comment by seratch** [comment]
Could you share the actual screenshot on Slack?

**Comment by anatolyw** [comment]
![Screen Shot 2019-05-29 at 10 03 27](https://user-images.githubusercontent.com/16581001/58540172-1e7f2680-81f9-11e9-84f9-b3bc25c05908.png)

**Comment by seratch** [comment]
Thanks. hmm, I'm not sure about the cause of it yet. What happens if you send the same parameters via `curl`?

**Comment by anatolyw** [comment]
do you have curl example to insert emoji?

**Comment by seratch** [comment]
https://api.slack.com/tutorials/slack-apps-hello-world#implement_the_webhook
parameter names need to be snake-cased (e.g., iconEmoji -> icon_emoji)

**Comment by anatolyw** [comment]
I have tried following documentation as:
`curl -X POST -H 'Content-type: application/json' --data '{"text":"Allow me to reintroduce myself!", "icon_emoji":"smiley_cat:"}'  YOUR_WEBHOOK_URL `
Result is the same: no emoji

**Comment by seratch** [comment]
Thanks. I'm still not sure why the emoji icon doesn't show up but now we figured out it's not a jSlack-specific issue.

**Comment by anatolyw** [comment]
honestly I cannot find even in the Slack spec for response payloads on different methods that emojis are supported. Maybe they were before, but not any more. Then it would be better to cleanup jslack API in order to avoid such questions. For now feel free to close this issue. Thanks for help.

**Comment by janmarcol** [comment]
Did you check your display settings in slack? I encountered the same issue and changed the setting in Preferences => Messages & Media => Theme from Compact to Clean and the icon is displayed as expected.

**Comment by ladrone-vincet** [comment]
Hey, I encountered the issue again. Both `icon_url` and `icon_emoji` fields are in the Slack API documentation but doesn't seem to be working from activepieces. Neither custom call or a create message template. Any ideas for a workaround?

**Comment by seratch** [comment]
Have you added chat:write.customize scope when issuing the token? The scope is required for the optional parameters.

**Comment by eugene-deng** [comment]
Hi, I have the same issue and I added the `chat:write.customize` scope to the bot.

**Comment by seratch** [comment]
I'd recommend double-checking if you've re-installed the app with the added scope and icon_emoji string is correct.

**Comment by eugene-deng** [comment]
> I'd recommend double-checking if you've re-installed the app with the added scope and icon_emoji string is correct.

Hi - I reinstall the app after adding the scope. But i don't get where to set the `icon_emoji` string. In java sdk, the request builder has `iconEmoji` to set emoji.

**Comment by eugene-deng** [comment]
> I'd recommend double-checking if you've re-installed the app with the added scope and icon_emoji string is correct.

kk. I installed it myself but it doesn't work. I asked my admin to try and it works now.
