### ISSUE TITLE
Access to RTMStartResponse

### ISSUE THREAD

**Issue by pekim** [seratch/jslack#16]
I want access to `RTMStartResponse`. Unfortunately `RTMClient rtm = new Slack().rtm(token)` (as suggested in the README) doesn't facilitate that.

After looking at https://github.com/seratch/jslack/blob/master/src/main/java/com/github/seratch/jslack/Slack.java#L66 I went for something like this.
```
Slack slack = Slack.getInstance();
RTMStartResponse rtmStartResponse = slack.methods()
			.rtmStart(RTMStartRequest.builder().token(token).build());
RTMClient rtmClient = new RTMClient(rtmStartResponse.getUrl());

System.out.println(rtmStartResponse.getTeam().getName());
System.out.println(rtmStartResponse.getUsers().size());
```
And I have the access that I'm after.

Although I'm only using public methods, I'm wondering if this is likely to be safe going forward. Am I using anything that not intended to be part of the public API?

**Comment by seratch** [comment]
There is no problem if you directly call methods API to start RTM.

**Comment by pekim** [comment]
Thank you for confirming that.
