### ISSUE TITLE
Missing Guest Channels Properties in User Profile

### ISSUE THREAD

**Issue by linlei99** [seratch/jslack#175]
Hi,

We have some invited guest users in our Slack. Two properties below are missing in the User Profile class which is causing Gson fails to convert the response Json string to Slack User objects.

"guest_channels" and "guest_invited_by" 

Could you please add them in User.java in the master branch so that we can keep our project going? 

Thank you so much.

Lei

**Comment by seratch** [comment]
Thanks for your pull request on this #176 
I will release a new version including the change very soon.

**Comment by seratch** [comment]
version 1.7.3 is out. Thank you for your feedback and contributions!

**Comment by linlei99** [comment]
Thank you so much!
