### ISSUE TITLE
Methods users.setPhoto and users.deletePhoto

### ISSUE THREAD

**Issue by vaniusrb** [seratch/jslack#18]
Hello guys! I'm really enjoying using this library, congratulations. 
I did not find the implementation for the "users.setPhoto" and "users.deletePhoto" methods. 
Is there any future plan to be implemented? Thank you.

**Comment by seratch** [comment]
@vaniusrb Ah, somehow, I forgot implementing them :(  Of course, I'd love to support all the methods.

Adding users.setPhoto is pretty easy. If you're interested in working on it, pull requests are always welcome.

https://github.com/seratch/jslack/blob/4f3ac15a6d3e09eb408c7ac60cbdfcd4fbcf28be/src/main/java/com/github/seratch/jslack/api/methods/impl/MethodsClientImpl.java#L442-L455

**Comment by vaniusrb** [comment]
@seratch Interesting, I'll try. Thanks for the reply.
