### ISSUE TITLE
Deserialize payload for interactive-messages

### ISSUE THREAD

**Issue by silentsnooc** [seratch/jslack#181]
I am currently trying to deserialize the payload which I receive as somebody clicks on a interactive button.

For this I have a basic endpoint which Slack sends a POST with the payload string:

```java
@RequestMapping(value = "/slack/action", method = RequestMethod.POST)
public Object action(
        @RequestParam(name = "payload") String payload
) {
    // ..
}
``` 

but I am not sure how I can use jslack to read this payload. Is this even possible? I couldn't find something.

> **Note:** I am following this new approach https://api.slack.com/messaging/interactivity

**Comment by seratch** [comment]
You can bind request body to these classes> https://github.com/seratch/jslack/tree/1.7.4/jslack-app-backend/src/main/java/com/github/seratch/jslack/app_backend/interactive_messages/payload

**Comment by silentsnooc** [comment]
@seratch Can I? If I try this:

```java
@RequestMapping(value = "/slack/action", method = RequestMethod.POST)
public Object action(@RequestBody BlockActionPayload blockActionPayload) {
    return null;
}
```

it does not work. Do I have to set something in additional here in order to make it work?

**Comment by seratch** [comment]
Ah, the JSON value will be given as `payload` parameter like `payload=%7B%22type%22%3A%22block_actions%22%2C%22team%22...
`

**Comment by silentsnooc** [comment]
@seratch Yes, it does seem so. I didn't find that information in the Slack docs. I found that only by taking a look at the `HttpServletRequest request` instance. 

But I have already tried

```java
BlockActionPayload pl = gson.fromJson(payload, BlockActionPayload.class);
```

without success.

**Comment by seratch** [comment]
Ah, this library has its own type adapters. Please use `com.github.seratch.jslack.common.json .GsonFactory`> https://github.com/seratch/jslack/blob/1.7.4/jslack-api-client/src/main/java/com/github/seratch/jslack/common/json/GsonFactory.java

**Comment by silentsnooc** [comment]
@seratch Awesome! Didn't know that. Works without a problem now. I see there are two ways to create a Gson object. I just used `GsonFactory.createSnakeCase()` without providing a configuration:

```java
Gson snakeCase = GsonFactory.createSnakeCase();
BlockActionPayload pl = snakeCase.fromJson(payload, BlockActionPayload.class);
```

I guess that issue can be closed :)

**Comment by seratch** [comment]
I'm glad to be of your help. Let me close this issue now. Thank you for using this library! 😃

**Comment by silentsnooc** [comment]
@seratch Thanks for providing this library :)
