### ISSUE TITLE
remove extra dependencies....

### ISSUE THREAD

**Issue by mbfbsae90** [seratch/jslack#19]
non documented dependencies:
If it is "simple" why do I need to keep adding libraries.

okhttp3/RequestBody
slf4j
org.slf4j.impl.StaticLoggerBinder
lombok

**Comment by seratch** [comment]
jSlack uses minimum necessary libraries.

- okhttp for HTTP requests
- slf4j for logging

The library users don't depend on Lombok. Lombok is needed only for compilation phase.

I'm not planning to remove the above dependencies.
