### ISSUE TITLE
Conversation model mismatches type for "is_moved"

### ISSUE THREAD

**Issue by jlorper** [seratch/jslack#208]
I recently updated the library from 1.5.7 to 1.8.1 and got the following exception 
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 296 path $.channels[0].is_moved`

Seems this new field "is_moved" was added on PR #169 [line](https://github.com/seratch/jslack/pull/169/files#diff-271b50cd9210c321a801dcf1355b09e9R74
)
```java
    @SerializedName("is_moved")
    private boolean isMoved;
```

But the sample is set as integer [line](https://github.com/seratch/jslack/pull/169/files#diff-c6c47c2b821f90bf978dbf101ae39129R48)
```json
    "is_moved": 12345,
```
This field is present since 1.7.2

I don't use this field so I'm not sure the impact of changing it. Slack's API doesn't provide much info on what the value is (or I'm not able to find it).
In the meantime I'll be back to 1.7.1

Thanks for the library!

**Comment by seratch** [comment]
Ah, my bad. We should have tests to verify jslack successfully parses sample JSON data. Will fix this very soon and release a new version asap.
