### ISSUE TITLE
ConfirmationMessage don't appear to work.

### ISSUE THREAD

**Issue by bensusman** [seratch/jslack#21]
Following the code it appears the naming convention for confirmation messages is incompatible with Slack at the moment.

I pinpointed the issue to here `String json = GsonFactory.createSnakeCase().toJson(req.getAttachments());` in `MethodsClientImpl.java`

The outputted json includes "confirmation_message". It should be "confirm".

The primary issue is the class name from what I can tell. 
`ConfirmationMessage` -> `Confirm` should fix the issue.

I'm not sure if the issue has arisen due to a change in Slack.

Below is the supporting documentation for the confirm button syntax (I don't know if they changed prior)
https://api.slack.com/docs/message-buttons

**Comment by bensusman** [comment]
Apologies. It is associated by the `Action` field name, not the classname, correct?

I tried to clone the repo, and make the change myself and make a PR and what not, but I seem to be having some issues getting Eclipse to work nicely with Lombok.

**Comment by seratch** [comment]
I don't understand what the points we need to change in the library code are. If you need to specify the value of `attachments.actions.name`, your own code can (to be exact, should) do that.

**Comment by bensusman** [comment]
The issue is not with the `attachments.actions.name` the issue is with `attachments.actions.confirm`. 

For example an action _should_ have the following json:
```
                {
                    "name": "game",
                    "text": "Thermonuclear War",
                    "style": "danger",
                    "type": "button",
                    "value": "war",
                    "confirm": {
                        "title": "Are you sure?",
                        "text": "Wouldn't you prefer a good game of chess?",
                        "ok_text": "Yes",
                        "dismiss_text": "No"
                    }
                }
```        
but the Json output from jslack is:
```
                {
                    "name": "game",
                    "text": "Thermonuclear War",
                    "style": "danger",
                    "type": "button",
                    "value": "war",
                    "confirmation_message": {
                        "title": "Are you sure?",
                        "text": "Wouldn't you prefer a good game of chess?",
                        "ok_text": "Yes",
                        "dismiss_text": "No"
                    }
                }
```     
Noting the difference between **confirm** and **confirmation_message**.

Does that clarify the the issue?

**Comment by seratch** [comment]
Thanks, I understand. So this pull request originally had a bug. https://github.com/seratch/jslack/pull/12

It's pretty easy to fix this. Just renaming the `ConfirmationMessage` class to `Confirm` class. You don't need to setup your Eclipse for Lombok. Simply building with Gradle and ensuring the behavior by running tests would be enough. I'm looking forward to merging your pull request 😸
