### ISSUE TITLE
Include Attachment type in Messages

### ISSUE THREAD

**Issue by ajurasz** [seratch/jslack#24]
As stated in the documentation:

`Messages can also include an attachments property, containing a list of attachment objects.`

Here is the structure of the attachment object https://api.slack.com/docs/message-attachments#attachment_structure.

The main goal of this feature is to create new type `Attachment` and add it to existing `Message` type. This way when I will be doing a fetch of channel history I will be able to retrieve fo instance posted URLs.

**Comment by ajurasz** [comment]
I will provide PR for this one.

**Comment by seratch** [comment]
Thank you. I'm looking forward to merging your 2nd contribution 👍
