### ISSUE TITLE
Incorrect BlockActionPayload definition

### ISSUE THREAD

**Issue by Kreisis** [seratch/jslack#249]
The Action class has a field initialOption of type Option, however, it is not correct,.
It works alright when the block action is submitted through a button click, however it does not work with static inputs.
![paveikslas](https://user-images.githubusercontent.com/22618169/68039456-d77bec80-fcd4-11e9-949d-9f5298533d6b.png)
![paveikslas](https://user-images.githubusercontent.com/22618169/68039647-3f323780-fcd5-11e9-923c-a88444de6d53.png)
![paveikslas](https://user-images.githubusercontent.com/22618169/68039706-5e30c980-fcd5-11e9-8896-12e8f91490b8.png)

**Comment by seratch** [comment]
Thanks for flagging this! I've created a PR to fix this.
