### ISSUE TITLE
Slash Command Example

### ISSUE THREAD

**Issue by prakashsvmx** [seratch/jslack#250]
Please provide Slash Command Example

**Comment by seratch** [comment]
Here are example apps for slash command:
* https://github.com/seratch/jslack/blob/master/jslack-app-backend/src/test/java/test_with_remote_apis/commands/SlashCommandApiBackend.java
* https://github.com/seratch/jslack/blob/master/jslack-lightning-docker-examples/echo-command-app/src/main/kotlin/App.kt

**Comment by seratch** [comment]
@prakashsvmx Let me know if you need more information. If I don't hear from you for a few days, allow me to close this issue.

**Comment by prakashsvmx** [comment]
Thank you.
