### ISSUE TITLE
Please give provision to set slack API endpoint URL prefix in SlackConfig

### ISSUE THREAD

**Issue by d-subrahmanyam** [seratch/jslack#260]
Can you please give provision to set slack API endpoint URL prefix in SlackConfig? 

This would be helpful in-case we are trying to call from behind a proxy.

**Comment by seratch** [comment]
@d-subrahmanyam Doesn't configuring okhttp client to have proxy setting work for you? (like https://github.com/seratch/jslack/commit/652ac1800a5c3a8bd49c6ec99e9a09b3795a6330 ) Is modifying the Slack API url required?

**Comment by d-subrahmanyam** [comment]
@seratch The reason I was requesting to have the slack API endpoint URL prefix in the SlackConfig is enable application integrations which sit behind a firewall and have proxied URL's to the actual Slack API endpoint URL. 

In that case the slack-app post their request to the proxy end-point URL, which in-turn makes the actual POST to the slack-endpoint URL.

**Comment by d-subrahmanyam** [comment]
@seratch Thank you.  👍
