### ISSUE TITLE
Users invitation endpoint

### ISSUE THREAD

**Issue by Yaskier** [seratch/jslack#27]
Slack has some secret endpoints that are so useful, one example is the user invitation endpoint:
https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md
Could you add this endpoint, in order to invite people to slack via API?

**Comment by seratch** [comment]
@Yaskier Sorry for my late response. If you can support this endpoint, it would be fine. Contributing to jSlack is quite easy. If you're interested in working on this, I'd love to merge your pull request.

**Comment by Yaskier** [comment]
I'll try to make some time!

**Comment by Roach** [comment]
FYI the invite endpoint is an undocumented admin endpoint and as such,  consistency is not guaranteed. The payload structure, fields and format may change at any time.

**Comment by seratch** [comment]
@Yaskier Please allow me to close this issue. I would like to implement only documented APIs in this project.
