### ISSUE TITLE
Add undocumented/legacy token API methods

### ISSUE THREAD

**Issue by marcinkunert** [seratch/jslack#287]
I wonder if you considered adding undocumented/legacy methods.

I've consider it useful because it allows to invite users to workspace without Enterprise Grid.

Here you can find unofficial docs for it: https://github.com/ErikKalkoken/slackApiDoc

**Comment by seratch** [comment]
@marcinkunert I know some of undocumented APIs are useful for specific use cases, but this library supports only documented ones.

**Comment by seratch** [comment]
As I mentioned above, this project won't support undocumented APIs but you can freely implement whatever you want using these new exposed methods in https://github.com/seratch/jslack/pull/290 on your end.

Allow me to close this issue by having an alternative way.
