### ISSUE TITLE
thread_ts to ChatPostEphemeralRequest

### ISSUE THREAD

**Issue by jtalacka** [seratch/jslack#295]
Hello, it seems that the classChatPostMessageRequest.java has Thread_ts support, but ChatPostEphemeralRequest.java doesnt. When looking at the documentation of slack api
chat.postEphemeral should have thread_ts support https://api.slack.com/methods/chat.postEphemeral
If it's not too much work maybe you can add this functionality?

**Comment by seratch** [comment]
@jtalacka Thanks for the feedback. I just shipped version 3.2.3 including the fix #296 . Try it out 👍
