### ISSUE TITLE
Fields in BlockActionPayload

### ISSUE THREAD

**Issue by dbp-stanford** [seratch/jslack#300]
I am trying to use com.github.seratch.jslack.app_backend.interactive_messages.payload.BlockActionPayload
to respond to a button press in Slack.  I'm using Jackson to create an instance of this class from the payload sent to me from Slack.

However, many field names in this class and embedded objects had different names in the class, from those provided in the payload.  These vary systematically, E.g. apiappid in the class is api_app_id in the payload, similarly for trigger_id and response_url.

Within the Team object, the payload contains enterprise_id and enterprise_name.
The User object contains user_id.

and so on.

**Comment by seratch** [comment]
The only way to correctly parse/write JSON data is to use gson with some additional configurations enabled here: https://github.com/seratch/jslack/blob/baddda32ce254993f29647a85dd2b709ce2ff88b/jslack-api-client/src/main/java/com/github/seratch/jslack/common/json/GsonFactory.java

Consider using gson for the classes in this library. I don’t have any plans to support jackson in the short term as it’s tough for this library to guarantee it works regardless of the differences among jackson’s versions.

**Comment by dbp-stanford** [comment]
Thanks.  わかりました。
