### ISSUE TITLE
How to get the result of what user clicked in interactive buttons ?

### ISSUE THREAD

**Issue by itayktest** [seratch/jslack#34]
I Add an interactive button but I cant get the selected button with the RTM
Can you assist, please?

**Comment by joeltoby** [comment]
Button clicks are not slack events - they are not provided by the RTM API.

Button clicks require a callback handler /URL which is out of scope for this library.

Please see the 'Responding to message actions' section of the doc: https://api.slack.com/docs/message-buttons

**Comment by itayktest** [comment]
Thanks for fast response 
Will this option be someday in this library?

**Comment by seratch** [comment]
Right, I don't have any plans to do something.

**Comment by seratch** [comment]
After 1.5 years, I've implemented some features to easily build a Slack App backend to handle the scenario discussed here. Actually, it's not possible to receive the event as an RTM events, but we can receive [interactive messages](https://api.slack.com/messaging/interactivity) on our side side.

Check the classes under [this package](https://github.com/seratch/jslack/blob/1.5.5/src/main/java/com/github/seratch/jslack/app_backend/interactive_messages/payload/). I've already started using these classes for my personal Slack apps.

For example, let's say a user clicks a button in a message made of [BlockKit components](https://api.slack.com/block-kit). At the time, your Slack App backend receives a HTTP request from Slack Platform. The request body contains a payload which has the type `block_actions` as below. You can use [this class](https://github.com/seratch/jslack/blob/1.5.5/src/main/java/com/github/seratch/jslack/app_backend/interactive_messages/payload/BlockActionPayload.java) to bind the request body. [Here](https://github.com/seratch/jslack/blob/1.5.5/src/test/java/app_backend/aws/InteractiveMessagesHandler.java) is a simple example code.

* BlockKit document: https://api.slack.com/reference/messaging/block-elements
* [Block examples](https://api.slack.com/tools/block-kit-builder?blocks=%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22This%20is%20a%20section%20block%20with%20a%20button.%22%7D%2C%22accessory%22%3A%7B%22type%22%3A%22button%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Click%20Me%22%7D%2C%22value%22%3A%22click_me_123%22%2C%22action_id%22%3A%22button%22%7D%7D%2C%7B%22type%22%3A%22actions%22%2C%22block_id%22%3A%22actionblock789%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22button%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Primary%20Button%22%7D%2C%22style%22%3A%22primary%22%2C%22value%22%3A%22click_me_456%22%7D%2C%7B%22type%22%3A%22button%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Link%20Button%22%7D%2C%22url%22%3A%22https%3A%2F%2Fapi.slack.com%2Fblock-kit%22%7D%5D%7D%5D)

<img width="800" src="https://user-images.githubusercontent.com/19658/57342216-c5335280-7178-11e9-9f2c-650babb56d66.png">

**Comment by seratch** [comment]
Please allow me close this issue. Feel free to reopen this when you have something to discuss further here at any time.
