### ISSUE TITLE
payload.channel() doesn't work for me

### ISSUE THREAD

**Issue by Geanik** [seratch/jslack#35]
in your src-files' comments i found the description of the Payload's "channel()"-method
if i'm not wrong, i should be able to write to another channel, than the webhook specifies
for me that doesn't work

i created a webhook for my "#general" channel, and want to send a message to the "#random" channel

`Payload payload = Payload.builder()
			.channel("#random")`

i've used that code at payload's building, but it still sends to "#general"
is there something I'm not seeing?
thx

**Comment by seratch** [comment]
Try this test code. It works. https://github.com/seratch/jslack/blob/c72cea1dca64e9999b6daf26b9e0217440c1267c/src/test/java/com/github/seratch/jslack/Slack_incomingWebhooks_Test.java

**Comment by Geanik** [comment]
thx for the quick response
i think i've found my problem
i want to use it with an "Slack App", where i created the WebHook
testing it with that url, didn't work

now i've created a "Incoming Webhooks" Custom Integration
with that it works

apparently it doesn't work with a "Slack App", but i need a slack app because i want to use "Interactive Message Buttons"
do you have any experience with overwriting the channel at Slack-Apps' WebHooks?

**Comment by joeltoby** [comment]
>You cannot override the default username, icon, or channel for incoming webhooks attached to Slack apps. Instead, these values will stubbornly inherit from the associated Slack app configuration.

From: https://api.slack.com/incoming-webhooks

**Comment by Geanik** [comment]
ok i have now found what i needed
i needed an app where the interactive messaging stuff was configured
and now i use the app's wrapped bot user to interact with users and send them interactive buttons, and the app's configuration gets used

thx for your help
