### ISSUE TITLE
Refactor all tests with Mock API calls

### ISSUE THREAD

**Issue by joeltoby** [seratch/jslack#36]
Mocking Slack API requests instead of making real calls will improve the tests and enable us to test calls that cannot be tested in an automated fashion without mocks such as `dialog.open` requests.

Slack's API team recently released [Steno](https://github.com/slackapi/steno):
> _Slack app testing companion - Record and Replay your HTTP requests, both incoming and outgoing_

I would like to integrate Steno into JSlack and replace all existing tests with Steno mock scenarios.

**Comment by joeltoby** [comment]
@seratch As discussed, please feel free to assign this to me.

**Comment by seratch** [comment]
Already two years have passed you posted this issue. 😅 Indeed, using Steno may be fine but I'm still not sure if we can maintain the assets to keep them up-to-date.

Also, this project has a server-side framework, Lightning. It's pretty easy to make sure if an app works as expected by running it like this: https://github.com/seratch/jslack/blob/3.2.0/jslack-lightning/src/test/java/samples/DialogSample.java

I myself don't see any inconvenience so far but I'm open to suggestions from anyone.

**Comment by joeltoby** [comment]
Hi @seratch ,  I can't believe it's been two years already!

I agree RE maintaining the assets.  Although it has a record function (which helps), its very difficult to know which responses may have changed without API versioning.

It might be worth looking at this again if the API becomes versioned and we get a change list on a regular basis.
