### ISSUE TITLE
Implement `conversations` API

### ISSUE THREAD

**Issue by joeltoby** [seratch/jslack#37]
From [the docs](https://api.slack.com/docs/conversations-api):

> The new Slack Conversations API provides your app with a unified interface to work with all the channel-like things encountered in Slack; public channels, private channels, direct messages, group direct messages, and our newest channel type, Shared Channels.The new Slack Conversations API provides your app with a unified interface to work with all the channel-like things encountered in Slack; public channels, private channels, direct messages, group direct messages, and our newest channel type, Shared Channels.

@seratch - I'm happy to do this if you agree that it adds value?

**Comment by seratch** [comment]
@joeltoby Of course, I agree. I would love to cover all Slack APIs.
