### ISSUE TITLE
Allow configuring URL prefixes

### ISSUE THREAD

**Issue by cesdperez** [seratch/jslack#38]
First, thanks for your sharing jslack 👍 

I'm using the Slack Methods client and I noticed the API prefix is hardcoded in a `static final` variable in `MethodsClientImpl#ENDPOINT_URL_PREFIX`. It'd be very useful if we could override those prefixes from outside.

A common scenario is when you want to use something like [wiremock](http://wiremock.org/) for writing integration tests using mock calls. In those cases you need to hit the stub server instead of the real one, so you need to configure a different URL prefix. You'll need this for #36 too. I could send you a PR if you don't mind.

**Comment by seratch** [comment]
Allowing to configure the URL prefixes would be great.
