### ISSUE TITLE
Reuse the httpClient?

### ISSUE THREAD

**Issue by esiqveland** [seratch/jslack#39]
At the first line in the `.send(url, payload)` the httpclient is created again every time, even though the instance has a slackhttpclient in its member variables.
https://github.com/seratch/jslack/blob/c5c2a1ff42cad3297694055306da1255fda2411a/src/main/java/com/github/seratch/jslack/Slack.java#L50

Should this rather be `this.httpClient`?

**Comment by seratch** [comment]
If you would like to reuse the client instance, simply reuse the `SlackHttpClient` instance. `Slack.getInstance()` does. https://github.com/seratch/jslack/blob/7ad360f07b57eff2aaf24b8c8f7690ea311132d9/src/main/java/com/github/seratch/jslack/Slack.java#L26

**Comment by esiqveland** [comment]
I am doing this, ie. `Slack.getInstance().send(...)`.

The send() method doesn't reuse, but creates a new httpClient.

`new SlackHttpClient()` calls the constructor which create a new instance of OkHttpClient:

```java
    public SlackHttpClient() {
        this.okHttpClient = new OkHttpClient.Builder().build();
    }
```

so even if I am using the singleton instance, it creates a new OkHttpClient on every message posted.

**Comment by seratch** [comment]
I see. Now I understand your point. You’re right.

**Comment by esiqveland** [comment]
Also, thank you for a great API client for talking to Slack!

**Comment by esiqveland** [comment]
Do you want me to have a go at it?

**Comment by seratch** [comment]
I would appreciate it if you could work on it.

**Comment by seratch** [comment]
Fixed by https://github.com/seratch/jslack/pull/46
