### ISSUE TITLE
Request to add to Message object

### ISSUE THREAD

**Issue by scoobymib3** [seratch/jslack#43]
Hi,

Love this project, saving me a bunch of time and effort! Thank you!

Can you add the bot_id, username and subtype to the Message object please? If you post with a custom username it is stored in the Message username field which I can't access.

cheers
Martin

**Comment by seratch** [comment]
https://api.slack.com/methods/channels.history#response

Indeed, those fields exist. Can you send a pull request to update the object? It's pretty easy. https://github.com/seratch/jslack/blob/master/src/main/java/com/github/seratch/jslack/api/model/Message.java

**Comment by scoobymib3** [comment]
Have done, must first pull request but think I've done it correctly
