### ISSUE TITLE
delete user method

### ISSUE THREAD

**Issue by davidkarlsen** [seratch/jslack#48]
I cannot find this call in the API: https://api.slack.com/scim#delete-users-id is it not implemented?

**Comment by seratch** [comment]
Not yet.

**Comment by davidkarlsen** [comment]
Should I do a PR - or do you already have something cooking for this?

**Comment by seratch** [comment]
I myself don’t have a plan to work on this in the near future. If you make a  pull request, I would love to merge it.

**Comment by davidkarlsen** [comment]
Hmm, I don't see any HTTP DELETE [1] options for the okhttp api: https://square.github.io/okhttp/3.x/okhttp/

[1]
https://api.slack.com/scim#delete-users-id

**Comment by davidkarlsen** [comment]
Ah - found it https://square.github.io/okhttp/3.x/okhttp/okhttp3/Request.Builder.html#delete--

**Comment by davidkarlsen** [comment]
Great - thanks!
