### ISSUE TITLE
Can't post as a user

### ISSUE THREAD

**Issue by k33g** [seratch/jslack#5]
Hey 👋 @seratch   If I read this code:
https://github.com/seratch/jslack/blob/master/src/main/java/com/github/seratch/jslack/shortcut/impl/ShortcutImpl.java#L122

`post` and `postAsBot` do exactly the same thing, for `post` the call of `_post()` should be `_post(channel, text, Collections.emptyList(), true);` (with `true` and not `false`)

```java
    @Override
    public ChatPostMessageResponse post(ChannelName channel, String text) throws IOException, SlackApiException {
        return _post(channel, text, Collections.emptyList(), false);
    }

    @Override
    public ChatPostMessageResponse postAsBot(ChannelName channel, String text) throws IOException, SlackApiException {
        return _post(channel, text, Collections.emptyList(), false);
    }
```

**Comment by seratch** [comment]
oops, thanks. I'll fix it soon.
