### ISSUE TITLE
Add additional response data from the rtm.start method

### ISSUE THREAD

**Issue by mkobit** [seratch/jslack#6]
The https://api.slack.com/methods/rtm.start method has additional fields like:

- `self`
- `team`
- `ims`
- `channels`
- `users`
- `groups`

It would be useful if those were available in the [RTMStartResponse](https://github.com/seratch/jslack/blob/master/src/main/java/com/github/seratch/jslack/api/methods/response/rtm/RTMStartResponse.java) for use when starting up an RTM connection.

**Comment by seratch** [comment]
That's true. However, I myself am not in a hurry on this. Pull requests are always welcome.

**Comment by seratch** [comment]
Thank you for your contribution 🎉
