### ISSUE TITLE
Few Questions on Slack 

### ISSUE THREAD

**Issue by ashwinbiyani** [seratch/jslack#63]
1. How can I send a scrollable data grid to slack as an incoming webhook response? Given it supports the only image format.
2. Can I send an image object as streaming content to incoming webhook response? or I need to publish this image object as an image in some folder and provide that URL as an attachment.
3. Now I have an app on my slack account. How do I make it available for my client's account and their workspace?
4. How about security. Can I put security on this slack app(which I created) so that only legitimate user, workspaces and accounts can only access this App? 
   - My workflow  - Every time a question is asked on Slack app, it hits my rest endpoint and once the question is processed I post the answer on incoming webhook. 
       How do I put security on each such transactions? so that it is secured.

I am little confused in terms of where and all security is required. I did go through manage distribution and OAuth sections in Slack doc but couldn't completely comprehend. Where to start, etc.

Appreciate, if you can answer my queries. I am simultaneously checking with Slack Team as well.

**Comment by Roach** [comment]
>How can I send a scrollable data grid to slack as an incoming webhook response? Given it supports the only image format.

You can't currently. You can experiment with different formatting options, though: https://api.slack.com/docs/messages/builder

>Can I send an image object as streaming content to incoming webhook response? or I need to publish this image object as an image in some folder and provide that URL as an attachment.
Now I have an app on my slack account. How do I make it available for my client's account and their workspace?

You'd have to use the Web API upload methods, rather than the response URL.

> How about security. Can I put security on this slack app(which I created) so that only legitimate user, workspaces and accounts can only access this App?

OAuth allows you to have your app authorized by specific users.

> How do I put security on each such transactions? so that it is secured.
I am little confused in terms of where and all security is required. I did go through manage distribution and OAuth sections in Slack doc but couldn't completely comprehend. Where to start, etc.

https://api.slack.com/docs/oauth-safety

**Comment by ashwinbiyani** [comment]
thanks very much Roach. Are there any charts like fusion charts , D3 are supported in Slack

**Comment by Roach** [comment]
@ashwinbiyani not currently. The most common solution is to render the chart as an iage and attach it to the message. One example would be StatsBot: https://statsbot.co/

![statsbot](https://mixpanel.com/wp-content/uploads/2016/06/2-showcases.gif)

**Comment by seratch** [comment]
@Roach Thank you for answering the questions.
@ashwinbiyani As the creator of this Java library, I do not have anything to do for this issue. Do you mind if I close this issue?

**Comment by ashwinbiyani** [comment]
Yes

**Comment by seratch** [comment]
I understand that you meant that you don't mind if I close this issue. If not, let me know. I will close this issue within a few days.

**Comment by ashwinbiyani** [comment]
Yes please, you can close.
