### ISSUE TITLE
Bubbling up HTTP 429s (too many requests)

### ISSUE THREAD

**Issue by joeltoby** [seratch/jslack#64]
Slack recently introduced a new rate-limiting system which is detailed [here](https://api.slack.com/docs/rate-limits).

As part of this, API methods now return an [HTTP 429](https://httpstatuses.com/429) response (too many requests) if limits are exceeded.  As is best practice, the 429 response is accompanied by a `retry-after` header.  This type of error is not returned as a JSON error object, but as a simple HTTP response.  Example from the [documentation section for 'responding to rate limit conditions'](https://api.slack.com/docs/rate-limits#headers):

 ```
HTTP/1.1 429 Too Many Requests

Retry-After: 30
```

Although it is correctly the responsibility of the client and not JSlack to implement rate limiting, the issue is that this error is not currently bubbled up to the client.  There is no way for example to access the value of the `Retry-After` header.

@seratch Do you have any thoughts on the best way to handle these HTTP 429 responses in JSlack?  Would it make sense to add a special case to the `SlackHttpClient.buildJsonResponse` method after the existing HTTP 200 handling?  E.G:
```
if (response.code() == 200) {
    ...
} else if (response.code() == 429) {
    ...
}
```

I guess that would also require changes to `SlackApiErrorResponse`?  Is there a better design?

**Comment by seratch** [comment]
In that case, SlackApiException would be thrown. You can access the header as below:

```java
} catch (SlackApiException e) {
  Optional<String> retryAfter = Optional.ofNullable(e.getResponse().header("Retry-After"));
}
```

**Comment by joeltoby** [comment]
Thanks @seratch. My silly mistake

**Comment by seratch** [comment]
Thanks for your reply. Let me close this issue.
