### ISSUE TITLE
cursor value missing from response_metadata for pagination.

### ISSUE THREAD

**Issue by samrajcse** [seratch/jslack#67]
Hi Team,

I am trying to do pagination for few API's but the cursor response from response_metadata is missing for other api other than Conversation. Now they support few other too. Also the classic pagination option is not provided. Any idea to support that too?

Reference: https://api.slack.com/docs/pagination

**Comment by seratch** [comment]
I see. Let me know the missing response attributes. I will fix the responses to have them.

**Comment by Anusien** [comment]
ChannelsListResponse is missing response_metadata.

**Comment by RishabhTayal** [comment]
@seratch Should I take a stab at implementing this?

**Comment by seratch** [comment]
I've automated the detection of missing attributes in responses. Thanks to that, I believe that I managed to add missing attributes like the `response_metadata` pointed out here. https://github.com/seratch/jslack/blob/1.5.2/src/main/java/com/github/seratch/jslack/api/methods/response/conversations/ConversationsListResponse.java#L20

Please allow me to close this now. But, if you find something wrong or missing, please let me know here or by filing another issue.
