### ISSUE TITLE
Convert JSON into the objects used by this library

### ISSUE THREAD

**Issue by faissaloo** [seratch/jslack#69]
I need it so I can take the response from RTMMessageHandler and turn it into the corresponding object, this seems pretty fundamental so I'm guessing I'm just missing it.

**Comment by seratch** [comment]
Indeed, it may be useful for many users.

**Comment by joeltoby** [comment]
Unless I'm misunderstanding the question, JSlack already does that with GSON.  See how it's done in the tests for example: 
 https://github.com/seratch/jslack/blob/3864b4478d9bfe9497812700ff8e23ce1f8b1352/src/test/java/com/github/seratch/jslack/Slack_rtm_Test.java

RTMMessageHandler handler1 = (message) -> {
            JsonObject json = jsonParser.parse(message).getAsJsonObject();

**Comment by seratch** [comment]
@faissaloo I've added some supports for this since version 1.4.0. Try them out.

* https://github.com/seratch/jslack/blob/1.4.0/src/test/java/com/github/seratch/jslack/Slack_rtm_typesafe_Test.java
* https://github.com/seratch/jslack/tree/1.4.0/src/main/java/com/github/seratch/jslack/api/model/event

**Comment by faissaloo** [comment]
Sorry @seratch I'm no longer working with this library anymore.

**Comment by seratch** [comment]
Okay, thanks for your response. Let me close this.
