### ISSUE TITLE
Common interfaces for Request and Response

### ISSUE THREAD

**Issue by joeltoby** [seratch/jslack#7]
Hi @seratch,

Thanks for open-sourcing the great library.
What's your opinion on providing two common marker interfaces to be implemented by all request and response objects?  I.E. All requests implement `request` and all responses implement `response`.

In my opinion it would be extremely useful for developers in a number of situations I've encountered:
1. It would enable clients to decorate requests / response to add additional client data.
2. Type erasure (and the like).  The ability to do `Processor<Request>` would be a major plus.

If you're in favour, I'd be more than happy to create a pull request.  Please let me me know if you'd like me to do so.

Cheers, Joel

**Comment by seratch** [comment]
@joeltoby It's acceptable for me to have such interfaces. More explicit name such as SlackApiRequest or similar is more preferred.

**Comment by joeltoby** [comment]
Thanks for the fast reply.  I'll name the objects as suggested.
