### ISSUE TITLE
Workspace App, chatPostMessage returns as_user not supported

### ISSUE THREAD

**Issue by PeterL1n** [seratch/jslack#70]
The new API for workspace app for posting chat messages does not allow as_user been set. It is noted in the API page: https://api.slack.com/methods/chat.postMessage

In jSlack's implementation, as_user is always set to either true or false. However, slack API requires the as_user field to be left unset. If it is set to either true or false, the endpoint returns:
{
    "ok": false,
    "error": "as_user_not_supported"
}

**Comment by PeterL1n** [comment]
I would suggest modifying ChatPostMessageRequest, changing the boolean as_user to Boolean as_user, so that we can put in null for builder().asUser(null)

**Comment by seratch** [comment]
Fair enough. I just created a pull request. I will merge it and release a new version very soon.

**Comment by seratch** [comment]
I just released version 1.1.3.
