### ISSUE TITLE
Message format for files has changed / needs updating

### ISSUE THREAD

**Issue by bensusman** [seratch/jslack#78]
One important note is the changing of the message format from file -> files and some minor changes to the file object structure.

https://api.slack.com/changelog/2018-05-file-threads-soon-tread
- See *Events API changes* for example of the message format change

We've experienced at least one issue with our implementation due to Slack's lack of backwards compatibility on this

**Comment by seratch** [comment]
I overlooked this issue. Thank you for raising the issue. We need to update the library.

**Comment by seratch** [comment]
I've modified the `File` object by #115 . I will release a new version which includes the changes very soon.
