### ISSUE TITLE
No class def found during runtime. 

### ISSUE THREAD

**Issue by timkartar** [seratch/jslack#82]
Hi seratch !

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
        at com.github.seratch.jslack.common.http.SlackHttpClient.<clinit>(SlackHttpClient.java:12)
        at com.github.seratch.jslack.Slack.<clinit>(Slack.java:31)
        at com.redgold.raktim.cs727.MainActivity.openSlackGame(MainActivity.java:89)

This error keeps coming. Apparently your jar in Maven repository is not dependency complete? Please tell me a correct way to include the jar. Or, please, give me a workaround. I am depending on it.

**Comment by seratch** [comment]
I don't think so. It seems to be an issue in your project. By the way, are you going to use the library in an Android app? Unfortunately, the library depends on JDK 8+ which means it doesn't work with Android Java.

**Comment by timkartar** [comment]
Thanks a lot. That probably was the case. I found this API for android https://github.com/pschroen/slack-api-android to solve my case.
