### ISSUE TITLE
Mock/TestKit for Jslack

### ISSUE THREAD

**Issue by tomweinberg1** [seratch/jslack#83]
Hi,

There is any way to mock Jslack or TestKit for testing?

Thanks

**Comment by seratch** [comment]
Do you mean that you'd like to know ways to create mock objects for `com.github.seratch.jslack.Slack` type? If so, you should be able to do that with any mocking frameworks such as mockito.

**Comment by tomweinberg1** [comment]
I would link to use jslack at E2E and IT tests.
Use mockito is one of the solutions, But I am not sure it good enough for E2E tests.

**Comment by seratch** [comment]
I'm not sure what the E2E tests in your case actually are, but if you need a mock object for `Slack` objects or any classes in jSlack library, I believe that it should be possible without any problems. If a specific class can be a blocker for your testing, let me know. Let me close this issue. If you have additional topics or feature requests, feel free to open another one or re-open this.
