### ISSUE TITLE
Unable to post response message back to slack channel 

### ISSUE THREAD

**Issue by jamesrloveday** [seratch/jslack#86]
Hi this might be a bit noddy so forgive me if I'm missing something, I've worked off your docs and have produced this section of code to post a response back as a bot user to the originating channel. 

> 
Slack slack = Slack.getInstance();
        ApiToken token = ApiToken.of("TOKEN");

 if(message.event.text.contains("test")) {
            ChatPostMessageResponse postResponse = slack.methods().chatPostMessage(
                    ChatPostMessageRequest.builder()
                            .token(token.getValue())
                            .channel("<channelID>")
                            .text("Hello from bot")
                            .asUser(false)
                            .username("@aBot")
                            .build());
            assert postResponse.isOk();
        }

There seems to be an issue and I'm not sure if its the code or outside of that. 

The exception that I'm getting is connect timed out. 
I'm using ngrok to handle the tunnelling between slack and my local machine and have worked with it well enough over the last few days to handle communication between a service and a slash command, with the system set up in the same way I'm not having any issues. 

I am unable to get the connection between my local machine and slack to work correctly. Am I missing something. 
__

**Comment by seratch** [comment]
I'm not sure what your problem is yet.

**Comment by jamesrloveday** [comment]
So basically I'm trying to rule out that I have made an incorrect use of the code, from what I've posted going off the examples it seems as though it should be working, but isn't I'm not sure where the problem is but I'm attempting to rule out the code as the issue. If I can rule that out as the problem then I can look towards the corporate infrastructure, proving that the code isn't the issue.

**Comment by seratch** [comment]
Okay, I’m afraid that there is nothing to do on my side at this moment. Let me close this GirHub issue for now. When you detect something wrong in my library, please feel free to reopen this or create another one.
