### ISSUE TITLE
Support for the files.upload thread_ts argument

### ISSUE THREAD

**Issue by IARI** [seratch/jslack#87]
File upload apparently supports a thread_ts argument:
https://api.slack.com/methods/files.upload

Currently it is not part of the `FilesUploadRequest` class.
It would be very useful to include this parameter. unless it is currently with jslack possible to upload a file and post it as a response to a thread in another way

**Comment by seratch** [comment]
Thank you for your request. It seems to be fairly easy fix. If you're interested in contributing to this library and have time to work on it, could you send a pull request on this issue?

**Comment by seratch** [comment]
I had a time to work on this issue. I've fixed this by myself. #90

**Comment by seratch** [comment]
Just released in version 1.1.7
